// Code generated by coz. DO NOT EDIT.
/**
 * JS support version checker
 * @module the-support
 */
'use strict'

import TheSupport from './TheSupport'
import create from './create'

export {
  TheSupport,
  create,
}

export default create
