// Code generated by coz. DO NOT EDIT.
/**
 * JS support version checker
 * @module the-support
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get TheSupport () { return _d(require('./TheSupport')) },
  get create () { return _d(require('./create')) },
  get default () { return _d(require('./create')) },
}
